name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: evolene
      type: github
      name: KTH/evolene
      endpoint: github.com_jotunskij

jobs:
- job: run_evolene
  displayName: Build with Evolene
  continueOnError: true
  workspace:
    clean: outputs
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'
  - bash: pip install --upgrade pip
  - checkout: evolene
  - checkout: self
  #- bash: mkdir $EVOLENE_DIRECTORY/temp
  #- bash: pip install --target $EVOLENE_DIRECTORY/pipenv pipenv
  #- bash: mv -f $EVOLENE_DIRECTORY/temp/* $EVOLENE_DIRECTORY/pipenv
  - bash: pip install pipenv
  - bash: pipenv install
    workingDirectory: $EVOLENE_DIRECTORY
  - bash: $EVOLENE_DIRECTORY/run.sh
    workingDirectory: $(Agent.BuildDirectory)/s/$(Build.Repository.Name)

