name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: evolene
      type: github
      name: KTH/evolene
      endpoint: 
jobs:
- job: install_pip
  displayName: Install pip
  continueOnError: true
  workspace:
    clean: outputs
  steps:
  - bash: apt-get install pip
