name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: evolene
      type: github
      name: KTH/evolene
      endpoint: github.com_jotunskij

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

jobs:
- job: upgrade_pip
  displayName: Upgrade pip
  continueOnError: true
  workspace:
    clean: outputs
  steps:
  - bash: pip install --upgrade pip
  - bash: pip install pipenv
  - checkout: evolene
  - bash: $(Agent.BuildDirectory)/s/create_dist.sh

