name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: evolene
      type: github
      name: KTH/evolene
      endpoint: github.com_jotunskij

jobs:
- job: run_evolene
  displayName: Build with Evolene
  continueOnError: true
  workspace:
    clean: outputs
  variables:
    EVOLENE_DIRECTORY: $(Agent.BuildDirectory)/s/evolene
    WORKSPACE: $(Agent.BuildDirectory)/s/self
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

  - bash: pip install --upgrade pip

  - checkout: evolene
    path: evolene
  - checkout: self
    path: self

  - bash: pip install pipenv

  - bash: pipenv install
    workingDirectory: $(EVOLENE_DIRECTORY)

  - bash: ls -al
    workingDirectory: $(WORKSPACE)

  - bash: $EVOLENE_DIRECTORY/run.sh
    workingDirectory: $(WORKSPACE)

