name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: evolene
      type: github
      name: KTH/evolene
      endpoint: github.com_jotunskij

jobs:
- job: upgrade_pip
  displayName: Upgrade pip
  continueOnError: true
  workspace:
    clean: outputs
  steps:
  - bash: pip install --upgrade pip
  - bash: pip install pipenv
  - checkout: evolene
  - bash: ./create_dist.sh

