name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: evolene
      type: github
      name: KTH/evolene
      endpoint: github.com_jotunskij

jobs:
- job: run_evolene
  displayName: Build with Evolene
  continueOnError: true
  workspace:
    clean: outputs
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'

  - bash: pip install --upgrade pip

  - checkout: evolene
  - checkout: self

  - bash: pip install pipenv

  - bash: pipenv install
    workingDirectory: evolene

  - bash: ls -al
    workingDirectory: ${{replace(variables.Build.Repository.Name, 'KTH/', '')}}

  - bash: echo $WORKSPACE && $EVOLENE_DIRECTORY/run.sh
    workingDirectory: $(Agent.BuildDirectory)/s/$(replace(variables.Build.Repository.Name, 'KTH/', ''))
    env:
      WORKSPACE: $(Agent.BuildDirectory)/s/$(replace(variables.Build.Repository.Name, 'KTH/', ''))

